services/platform/daemon/communicate/client.go
services/platform/daemon/config.yaml
services/platform/daemon/go.mod
services/platform/daemon/go.sum
services/platform/daemon/host/rpc.go
services/platform/server/config.yaml
services/platform/server/daemon/commander.go
services/platform/server/daemon/rpc.go
services/platform/server/go.mod
services/platform/server/go.sum
services/platform/server/main.go
services/platform/server/web/rpc.go

Implemented the basic web server which handles restart and shutdown commands and sends them to the daemon. Also added a forward from the daemon to the server when a shutdown alert happens.

feat: basic daemon/server commands

---

services/platform/daemon/communicate/client.go
services/platform/daemon/execute/execute.go

Implementing actual execution of shutdown and restart commands from the server on the daemon.

feat: actually execute commands on daemon

---

services/platform/daemon/communicate/client.go
services/platform/daemon/config.yaml
services/platform/daemon/go.mod
services/platform/daemon/host/runner.go
services/platform/daemon/host/server.go
services/platform/daemon/main.go

Adding functionality to the daemon to identify the host's IP address at boot and update the kubernetes configuration with that value.
Also downgraded go to 1.22.3 since it appears nix-build doesn't yet support 1.22.5.

feat: auto-set host IP address

---

services/platform/daemon/communicate/client.go
services/platform/daemon/execute/execute.go
services/platform/daemon/versioning/controller.go

Found out these commands weren't working correctly. The fixes here add extra logging and error handling. The actual fix is in an upcoming PR in the `os` repo (was missing environment variables).

fix: daemon update check commands

---

services/platform/daemon/communicate/client.go

This should fix an edge case where the daemon cannot connect to the server at initial bootup and needs to restart. This PR adds logic to limit connection attempts to 25x (at one attempt per second) and then exits with code 1. systemd should restart the daemon on exit.

fix: daemon->server connection retry limit

---

Dockerfile
services/platform/server/web-client/src/services/web_rpc.js

Fixing bug where the production build is trying to connect to localhost.
Also cleaned up Dockerfile.

fix: NODE_ENV bug

---

services/platform/server/main.go
services/platform/server/web-client/src/pages/Dashboard.js
services/platform/server/web-client/src/pages/DefaultLayout.js
services/platform/server/web-client/src/pages/Device/Onboard.js
services/platform/server/web/controller.go
services/platform/server/web/rpc.go

update routing to work with login, and onboarding

update routing to work with login, and onboarding

---

services/platform/server/web-client/src/pages/Home/index.js
services/platform/server/web-client/src/services/web_rpc.js

basic installed apps list

---

Dockerfile
services/platform/server/web-client/src/services/web_rpc.js

Messed up the NODE_ENV with local instead of development last time. Fixing that as well as building production mode in the Dockerfile.

fix: NODE_ENV again

---

services/platform/server/web-client/src/pages/Dashboard.js
services/platform/server/web-client/src/pages/DefaultLayout.js
services/platform/server/web-client/src/pages/Device/Onboard.js
services/platform/server/web-client/src/pages/Home/index.js
services/platform/server/web-client/src/pages/Login.js

update routing in onboarding

---

services/platform/server/web-client/src/pages/Dashboard.js
services/platform/server/web-client/src/pages/DefaultLayout.js
services/platform/server/web-client/src/pages/Home/index.js
services/platform/server/web-client/src/pages/Settings/index.js

nav now works as it should

---

services/platform/server/web-client/src/pages/Settings/index.js
services/platform/server/web-client/src/services/web_rpc.js
services/platform/server/web/controller.go
services/platform/server/web/rpc.go

adding settings page with read only values and power button

adding settings page with read only values and power button

---

services/platform/server/web-client/src/pages/DefaultLayout.js

fix default routing

---

services/platform/daemon/communicate/client.go
services/platform/daemon/go.mod
services/platform/daemon/go.sum
services/platform/daemon/versioning/nix.go
services/platform/server/go.mod
services/platform/server/go.sum
services/platform/server/system/commander.go
services/platform/server/system/controller.go
services/platform/server/web-client/src/pages/Device/Onboard.js

Implemented logic on the Server and Daemon to set the time zone during the getting started flow.

feat: time zone implementation during getting started

---

services/platform/server/web-client/src/pages/Dashboard/index.js

if not setup route to home

---

services/platform/server/web-client/src/pages/Dashboard/index.js
services/platform/server/web-client/src/pages/Home/index.js

fix if no apps installed render still render home screen, and nav on home screen

fix if no apps installed render still render home screen, and nav on home screen

---

services/platform/server/apps/controller.go
services/platform/server/web-client/src/pages/Device/Onboard.js
services/platform/server/web-client/src/pages/Home/index.js
services/platform/server/web-client/src/pages/Settings/index.js
services/platform/server/web-client/src/services/web_rpc.js

Fixing some display bugs with the home page app list and fixing the wrong version being used during dependency installation.

fix: misc FE bugs

---

services/platform/server/web-client/src/pages/Device/Onboard.js

don't allow a user with a setup server back to the getting started page

don't allow a user with a setup server back to the getting started page

---

services/platform/server/web-client/src/pages/Dashboard/index.js
services/platform/server/web-client/src/pages/DefaultLayout.js
services/platform/server/web-client/src/pages/Device/Onboard.js

ahhh routing

---

services/platform/server/web-client/src/pages/Device/Onboard.js
services/platform/server/web-client/src/services/web_rpc.js

Adding client-side input validation

Adding client side input validation

---

services/platform/server/web-client/package-lock.json
services/platform/server/web-client/package.json
services/platform/server/web-client/src/pages/Device/Onboard.js

Adding user feedback when an error happens

Adding user feedback when an error happens

---

services/platform/server/web-client/src/pages/Device/Onboard.js

refine error clearing

---

services/platform/daemon/communicate/client.go
services/platform/server/apps/controller.go
services/platform/server/apps/store_cache.go
services/platform/server/system/commander.go
services/platform/server/system/controller.go

Fixing a few different bugs preventing auto-update to work across the OS, apps, and system containers.

fix: auto-update

---

services/platform/daemon/communicate/client.go
services/platform/daemon/go.mod
services/platform/daemon/go.sum
services/platform/server/go.mod
services/platform/server/go.sum
services/platform/server/system/controller.go
services/platform/server/system/server.go
services/platform/server/web/rpc.go

This PR consolidates the processing of the device initialization so that from the `web-client` it appears as a single synchronous call. This makes the error path easier for the user.

feat: synchronous device setup

---

services/platform/server/web-client/package-lock.json
services/platform/server/web-client/package.json
services/platform/server/web-client/src/pages/Dashboard/index.js
services/platform/server/web-client/src/pages/DefaultLayout.js
services/platform/server/web-client/src/services/event_stream.js
services/platform/server/web-client/src/services/web_rpc.js
services/platform/server/web-client/src/services/web_slice.js
services/platform/server/web-client/src/store/index.js

Setup redux middleware to subscribe to server events, heartbeat messages are ignored but others are pushed into redux state so they can be used with other components.

Setup redux middleware to subscribe to server events

---

services/platform/daemon/communicate/client.go
services/platform/server/go.mod
services/platform/server/go.sum
services/platform/server/system/controller.go
services/platform/server/web-client/package-lock.json
services/platform/server/web-client/package.json
services/platform/server/web-client/src/pages/Settings/index.js
services/platform/server/web-client/src/services/web_rpc.js
services/platform/server/web/rpc.go

Implements the functionality on the Settings page to actually change the device settings. This reuses the initialize path on the daemon for now. We should probably separate these in the future at some point.

feat: Set device settings

---

services/platform/server/web-client/src/pages/AppStore/index.js
services/platform/server/web-client/src/services/web_rpc.js
services/platform/server/web-client/src/services/web_slice.js

Adding reactivity to installedApp event

Adding reactivity to installedApp event

---

services/platform/server/web-client/src/pages/DefaultLayout.js

When a link is clicked close the off canvas nav

When a link is clicked close the off canvas nav

---

services/platform/operator/internal/controller/app_controller.go

Run creation/installation steps for all app dependencies (persistence, routes, etc.) on upgrade as well as install.

feat: attempt to create app dependencies on upgrade

---

services/platform/daemon/host/files.go
services/platform/server/system/os.go

Had the wrong file path for the server manifest and the timeout on the listener for the OS update check was too short.

fix: Update issues

---

services/platform/daemon/communicate/client.go
services/platform/daemon/host/nix.go
services/platform/server/go.mod
services/platform/server/go.sum
services/platform/server/system/containers.go
services/platform/server/web-client/package-lock.json
services/platform/server/web-client/package.json
services/platform/server/web-client/src/App.tsx
services/platform/server/web-client/src/pages/updates/Updates.tsx

Added an Updates page that lists all pending component updates and allows the user to update ad hoc.
Example:

feat: Updates page
